In [80]:
import sys
sys.path.append('../')
import numpy as np
from pychemkin import chemkin
demofile = 'demo_xml/rxns.xml'
rxnsystem = chemkin(demofile)
T = 1000 #temperature in K
x = np.array([0.5,0.5,0.5,0.5,0.5,0.5])
x = np.ones(6)
print("Progress rates")
print(rxnsystem.progress_rate(x,T))
print("Reaction rates")
print(rxnsystem.reaction_rate(x,T))

Finished reading xml input file
Progress rates
[  6.55925729e+06   2.69357993e+05   1.00000000e+03]
Reaction rates
[ -6.28889929e+06   6.28989929e+06   6.82761528e+06  -2.70357993e+05
   1.00000000e+03  -6.55925729e+06]


In [5]:
rxnsystem

chemkin('demo_xml/rxns.xml')

In [6]:
rxnsystem.species

['H', 'O', 'OH', 'H2', 'H2O', 'O2']

In [6]:
print(rxnsystem)

chemical equations:
[
H + O2 =] OH + O
H2 + O =] OH + H
H2 + OH =] H2O + H
]
species: ['H', 'O', 'OH', 'H2', 'H2O', 'O2']
nu_react:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 1]
 [0 0 0]
 [1 0 0]]
nu_prod:
[[0 1 1]
 [1 0 0]
 [1 1 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]]
reaction coefficients:
[
Arrhenius Reaction Coeffs: {'A': 35200000000.0, 'E': 71400.0, 'R': 8.314}
modifiedArrhenius Reaction Coeffs: {'A': 0.0506, 'b': 2.7, 'E': 26300.0, 'R': 8.314}
Constant Reaction Coeffs: {'k': 1000.0, 'R': 8.314}
]
reaction types: ['Elementary', 'Elementary', 'Elementary']
reversible: [False False False]
