In [1]:
%%bash
sudo pip install pychemkin

In [2]:
import numpy as np
from pychemkin import chemkin
demofile = 'demo_xml/rxns_reversible.xml'
rxnsystem = chemkin(demofile)
T = 999.99999 #temperature in K
x = [1,2,3,4,5,6,7,8]
print("Progress rates")
print(rxnsystem.progress_rate(x,T))
print("Reaction rates")
print(rxnsystem.reaction_rate(x,T))

Finished reading xml input file
Progress rates
[ -4.37918361e+16   1.06891625e+13   5.80849020e+13  -3.33238238e+15
   1.05248391e+14   4.78255724e+14   4.55000000e+14   6.44285996e+14
   1.19599129e+14   1.48165394e+14   9.47751873e+13]
Reaction rates
[  4.30093415e+16  -4.10199181e+16  -4.95223968e+16   1.84639721e+14
   4.15435240e+15   4.49963705e+16  -1.43984953e+15  -3.62539710e+14]


In [3]:
rxnsystem

chemkin('demo_xml/rxns_reversible.xml')

In [4]:
rxnsystem.species

['H', 'O', 'OH', 'H2', 'H2O', 'O2', 'HO2', 'H2O2']

In [5]:
print(rxnsystem)

['H + O2 [=] O + OH', 'O + H2 [=] H + OH', 'H2 + OH [=] H2O + H', 'O + H2O [=] OH + OH', 'HO2 + H [=] H2 + O2', 'HO2 + H [=] OH + OH', 'HO2 + O [=] O2 + OH', 'HO2 + OH [=] H2O + O2', 'H2O2 + H [=] H2O + OH', 'H2O2 + H [=] HO2 + H2', 'H2O2 + O [=] OH + HO2']
chemical equations:
[
H + O2 [=] O + OH
O + H2 [=] H + OH
H2 + OH [=] H2O + H
O + H2O [=] OH + OH
HO2 + H [=] H2 + O2
HO2 + H [=] OH + OH
HO2 + O [=] O2 + OH
HO2 + OH [=] H2O + O2
H2O2 + H [=] H2O + OH
H2O2 + H [=] HO2 + H2
H2O2 + O [=] OH + HO2
]
species: not specified
nu_react:
[[1 0 0 0 1 1 0 0 1 1 0]
 [0 1 0 1 0 0 1 0 0 0 1]
 [0 0 1 0 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1]]
nu_prod:
[[0 1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 2 0 2 1 0 1 0 1]
 [0 0 0 0 1 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 1 0 0]
 [0 0 0 0 1 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0]]
reaction coefficients:
[
modifiedArrhenius Reactio