In [1]:
# Required demo
from chemkin import *
reactions = chemkin.from_xml('rxns.xml')
x = np.array([1,1,1,1,1,1])
T = 1000
print(reactions.reaction_rate_T(x, T))
print(reactions.progress_rate(x))

Finished reading xml input file
[ -6.28889929e+06   6.28989929e+06   6.82761528e+06  -2.70357993e+05
   1.00000000e+03  -6.55925729e+06]
[  6.55925729e+06   2.69357993e+05   1.00000000e+03]


In [2]:
# If not from xml
rc_list = [
    ReactionCoeffs(type = "modifiedArrhenius", A=1e8, b=0.5, E=5e4),
    ReactionCoeffs(type = "Constant", k=1e4),
    ReactionCoeffs(type = "Arrhenius", A=1e7, E=1e4),
]
##Stoichiometric coeff for the reactants
#columns = reactions
#row is each species 
v1 = np.array([
    [2,0,0],
    [1,0,1],
    [0,1,0],
    [0,1,0],
    [0,0,1]
])
##Stoichiometric coeff for the products 
v2 = np.array([
    [1,0,0],
    [0,1,0],
    [2,0,1],
    [0,0,1],
    [0,1,0]
])

#[c] of each species 
x = np.array([
    2,1,0.5,1,1
])

rxn_types = ['Elementary']*5

reversible = ['no']*5

reactions = chemkin(v1,v2,rc_list, rxn_types, reversible)
for t in [750,1500,2500]:
    reactions.set_rc_params(T=t)
    print("Reaction rate")
    print(reactions.reaction_rate(x))

print(reactions)

Reaction rate
[-3607077.87280407 -5613545.1836208   9220623.05642486  2006467.31081673
 -2006467.31081673]
Reaction rate
[ -2.81117621e+08  -2.85597559e+08   5.66715180e+08   4.47993847e+06
  -4.47993847e+06]
Reaction rate
[ -1.80426143e+09  -1.81043736e+09   3.61469878e+09   6.17593098e+06
  -6.17593098e+06]
chemical equations: not specified
species: not specified
nu_react:
[[2 0 0]
 [1 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]]
nu_prod:
[[1 0 0]
 [0 1 0]
 [2 0 1]
 [0 0 1]
 [0 1 0]]
reaction coefficients:
[
modifiedArrhenius Reaction Coeffs: {'A': 100000000.0, 'b': 0.5, 'E': 50000.0, 'R': 8.314, 'T': 2500}
Constant Reaction Coeffs: {'k': 10000.0, 'R': 8.314, 'T': 2500}
Arrhenius Reaction Coeffs: {'A': 10000000.0, 'E': 10000.0, 'R': 8.314, 'T': 2500}
]
reaction types: ['Elementary', 'Elementary', 'Elementary', 'Elementary', 'Elementary']
reversible: ['no', 'no', 'no', 'no', 'no']


In [3]:
# If all reaction coeffs are constant (init with values [k])
reactions = chemkin.init_const_rc(v1,v2,[1,1,1],['Elementary']*5, ['no']*5, species = ['A','B','X','Y','Z'])
print(reactions.reaction_rate_T([1,1,1,1,1],1000))
print(reactions)

[-1. -1.  2.  0.  0.]
chemical equations: not specified
species: ['A', 'B', 'X', 'Y', 'Z']
nu_react:
[[2 0 0]
 [1 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]]
nu_prod:
[[1 0 0]
 [0 1 0]
 [2 0 1]
 [0 0 1]
 [0 1 0]]
reaction coefficients:
[
Constant Reaction Coeffs: {'k': 1, 'R': 8.314, 'T': 1000}
Constant Reaction Coeffs: {'k': 1, 'R': 8.314, 'T': 1000}
Constant Reaction Coeffs: {'k': 1, 'R': 8.314, 'T': 1000}
]
reaction types: ['Elementary', 'Elementary', 'Elementary', 'Elementary', 'Elementary']
reversible: ['no', 'no', 'no', 'no', 'no']


In [4]:
# set reaction coeffs variables on-the-fly
reactions = chemkin.from_xml('rxns.xml')
reactions.set_rc_params(T=1000) # set all params together
print(reactions.reaction_rate([1,1,1,1,1,1]))
print(reactions.rc_list[0])
#Index 0 for modifies 

#change the A param for rate coeff for modified 
reactions.rc_list[0].set_params(A=500) # only set one rc
print(reactions.reaction_rate([1,1,1,1,1,1]))

Finished reading xml input file
[ -6.28889929e+06   6.28989929e+06   6.82761528e+06  -2.70357993e+05
   1.00000000e+03  -6.55925729e+06]
Arrhenius Reaction Coeffs: {'A': 35200000000.0, 'E': 71400.0, 'R': 8.314, 'T': 1000}
[  2.70357900e+05  -2.69357900e+05   2.68358087e+05  -2.70357993e+05
   1.00000000e+03  -9.31712683e-02]


In [5]:
# special method
print(reactions)
print()
k=eval(repr(reactions))
print(k)
len(reactions) # number of reactions

chemical equations:
[
H + O2 =] OH + O
H2 + O =] OH + H
H2 + OH =] H2O + H
]
species: ['H', 'O', 'OH', 'H2', 'H2O', 'O2']
nu_react:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 1]
 [0 0 0]
 [1 0 0]]
nu_prod:
[[0 1 1]
 [1 0 0]
 [1 1 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]]
reaction coefficients:
[
Arrhenius Reaction Coeffs: {'A': 500, 'E': 71400.0, 'R': 8.314, 'T': 1000}
modifiedArrhenius Reaction Coeffs: {'A': 0.0506, 'b': 2.7, 'E': 26300.0, 'R': 8.314, 'T': 1000}
Constant Reaction Coeffs: {'k': 1000.0, 'R': 8.314, 'T': 1000}
]
reaction types: ['Elementary', 'Elementary', 'Elementary']
reversible: ['no', 'no', 'no']

chemical equations:
[
H + O2 =] OH + O
H2 + O =] OH + H
H2 + OH =] H2O + H
]
species: ['H', 'O', 'OH', 'H2', 'H2O', 'O2']
nu_react:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 1]
 [0 0 0]
 [1 0 0]]
nu_prod:
[[0 1 1]
 [1 0 0]
 [1 1 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]]
reaction coefficients:
[
Arrhenius Reaction Coeffs: {'A': 500, 'E': 71400.0, 'R': 8.314, 'T': 1000}
modifiedArrhenius Reaction Coeffs: {'A': 0.050

3